import CheckboxIcon from 'assets/svg/CheckboxIcon'
import DownArrowIcon from 'assets/svg/DownArrowIcon'
import PhoneIcon from 'assets/svg/PhoneIcon'
import RadioButtonIcon from 'assets/svg/RadioButtonIcon'
import TextAreaIcon from 'assets/svg/TextAreaIcon'
import UploadDocumentIcon from 'assets/svg/UploadDocumentIcon'
import CalendarIcon from 'assets/svg/CalendarIcon'
import { IFieldData } from 'interfaces'

export const formFields: IFieldData[] = [
  {
    id: 1,
    icon: <TextAreaIcon />,
    label: 'Text Field',
    type: 'text',
    isRequired: false,
    seqNumber: 1,
    pattern: '^[^\\s].*',
    defaultValue: '',
    name: '',
    description: '',
    scalarFieldId: 'scalarField',
    scalarFieldValue: 'value',
  },
  {
    id: 2,
    icon: <TextAreaIcon />,
    label: 'Text Area',
    type: 'text',
    isRequired: false,
    seqNumber: 1,
    pattern: '^[^\\s].*',
    defaultValue: '',
    name: '',
    description: '',
    scalarFieldId: 'scalarField',
    scalarFieldValue: 'value',
  },
  {
    id: 3,
    icon: <RadioButtonIcon />,
    label: 'Radio Button',
    type: 'radio',
    isRequired: false,
    seqNumber: 1,
    pattern: '',
    defaultValue: '',
    name: '',
    description: '',
    scalarFieldId: 'scalarField',
    scalarFieldValue: 'value',
  },
  {
    id: 4,
    icon: <CheckboxIcon />,
    label: 'Checkbox',
    type: 'checkbox',
    isRequired: false,
    seqNumber: 0,
    pattern: '',
    defaultValue: '',
    name: '',
    description: '',
    scalarFieldId: 'scalarField',
    scalarFieldValue: 'value',
  },
  {
    id: 5,
    icon: <DownArrowIcon />,
    label: 'Dropdown',
    type: 'dropdown',
    isRequired: false,
    seqNumber: 1,
    pattern: '',
    defaultValue: '',
    name: '',
    description: '',
    scalarFieldId: 'scalarField',
    scalarFieldValue: 'value',
  },
  {
    id: 6,
    icon: <UploadDocumentIcon />,
    label: 'Upload',
    type: 'file',
    isRequired: false,
    seqNumber: 1,
    pattern: '',
    defaultValue: '',
    name: '',
    description: '',
    scalarFieldId: 'scalarField',
    scalarFieldValue: 'value',
  },
  {
    id: 7,
    icon: <PhoneIcon />,
    label: 'Phone',
    type: 'number',
    isRequired: false,
    seqNumber: 1,
    pattern: '^[0-9]{0,}$',
    defaultValue: '',
    name: '',
    description: '',
    scalarFieldId: 'scalarField',
    scalarFieldValue: 'value',
  },
  {
    id: 8,
    icon: <DownArrowIcon />,
    label: 'Select',
    type: 'select',
    isRequired: false,
    seqNumber: 1,
    pattern: '',
    defaultValue: '',
    name: '',
    description: '',
    scalarFieldId: 'scalarField',
    scalarFieldValue: 'value',
  },
  {
    id: 9,
    icon: <CalendarIcon />,
    label: 'Date Picker',
    type: 'date',
    isRequired: false,
    seqNumber: 1,
    pattern: '',
    defaultValue: '',
    name: '',
    description: '',
    scalarFieldId: 'scalarField',
    scalarFieldValue: 'value',
  },
  {
    id: 10,
    icon: <CalendarIcon />,
    label: 'Time Picker',
    type: 'date',
    isRequired: false,
    seqNumber: 0,
    pattern: '',
    defaultValue: '',
    name: '',
    description: '',
    scalarFieldId: 'scalarField',
    scalarFieldValue: 'value',
  },
  {
    id: 11,
    icon: <UploadDocumentIcon />,
    label: 'Drag and Upload',
    type: 'file',
    isRequired: false,
    seqNumber: 0,
    pattern: '',
    defaultValue: '',
    name: '',
    description: '',
    scalarFieldId: 'scalarField',
    scalarFieldValue: 'value',
  },
]
