export const Dateformat = 'YYYY-MM-DD'

export const timeFormate = 'h:mm a'

export const DynamicData = [
  {
    defaultValue: '',
    description: '',
    icon: ' <RadioButtonIcon />',
    id: 'fb4480bd-84f7-4347-aee7-41cff0bd4a38',
    isDeleted: false,
    isRequired: true,
    label: 'Radio Button',
    name: 'Gender',
    option: [
      { label: 'option 1', value: '' },
      { label: 'option 2', value: '' },
      { label: 'option 3', value: '' },
      { label: '', value: '' },
    ],
    pattern: '',
    placeHolder: null,
    seqNumber: 1,
    type: 'radio',
    updatedAt: '2023-08-16T10:52:31.081Z',
  },
  {
    defaultValue: '',
    description: '',
    icon: ' <RadioButtonIcon />',
    id: 'fb4480bd-84f7-4347-aee7-41cff0bd4a38',
    isDeleted: false,
    isRequired: true,
    label: 'Radio Button',
    name: 'Language',
    option: [
      { label: 'option 1', value: 'option 1' },
      { label: 'option 2', value: 'option 2' },
      { label: 'option 3', value: 'option 3' },
      { label: 'option 4', value: 'option 4' },
    ],
    pattern: '',
    placeHolder: null,
    seqNumber: 1,
    type: 'checkbox',
    updatedAt: '2023-08-16T10:52:31.081Z',
  },
  {
    defaultValue: '',
    description: '',
    icon: ' <RadioButtonIcon />',
    id: 'fb4480bd-84f7-4347-aee7-41cff0bd4a38',
    isDeleted: false,
    isRequired: false,
    label: 'Radio Button',
    name: 'Graduation',
    option: [
      { label: 'option 1', value: '' },
      { label: 'option 2', value: '' },
      { label: 'option 3', value: '' },
      { label: '', value: '' },
    ],
    pattern: '',
    placeHolder: null,
    seqNumber: 1,
    type: 'select',
    updatedAt: '2023-08-16T10:52:31.081Z',
  },
  {
    defaultValue: '',
    description: '',
    icon: ' <RadioButtonIcon />',
    id: 'fb4480bd-84f7-4347-aee7-41cff0bd4a38',
    isDeleted: false,
    isRequired: false,
    label: 'Radio Button',
    name: 'Licence No',
    pattern: '',
    placeHolder: null,
    seqNumber: 1,
    type: 'text',
    updatedAt: '2023-08-16T10:52:31.081Z',
  },
  {
    defaultValue: '',
    description: '',
    icon: ' <RadioButtonIcon />',
    id: 'fb4480bd-84f7-4347-aee7-41cff0bd4a38',
    isDeleted: false,
    isRequired: true,
    label: 'Radio Button',
    name: 'City Name',
    pattern: '',
    placeHolder: null,
    seqNumber: 1,
    type: 'text',
    updatedAt: '2023-08-16T10:52:31.081Z',
  },
]

export const events = [
  { title: 'event 1', date: new Date('Thu Dec 14 2023 12:05:20 GMT+0530') },
  { title: 'event 2', date: '2019-04-02' },
]
