export const testData = [
  {
    id: 0,
    label: 'First Name',
    name: 'firstName',
    type: 'text',
    defaultChecked: false,
    isRequired: true,
    applicationType: 'profile',
    pattern: '^[^\\s].*',
  },
  {
    id: 1,
    label: 'Last Name',
    name: 'lastName',
    type: 'text',
    defaultChecked: false,
    applicationType: 'profile',
    isRequired: true,
    pattern: '^[^\\s].*',
  },
  {
    id: 2,
    label: 'Email ID',
    name: 'emailID',
    type: 'text',
    defaultChecked: false,
    applicationType: 'profile',
    isRequired: true,
    pattern: '^[a-zA-Z0-9.!#$%&’*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:.[a-zA-Z0-9-]+)*$',
  },
  {
    id: 3,
    label: 'Phone',
    name: 'phoneNumber',
    type: 'number',
    defaultChecked: false,
    isRequired: true,
    applicationType: 'profile',
    pattern: '^[0-9]{0,}$',
  },
  {
    id: 4,
    label: 'Resume(Attachment)',
    name: 'resume',
    type: 'file',
    defaultChecked: false,
    applicationType: 'profile',
    isRequired: true,
  },
  {
    id: 5,
    label: 'Address',
    name: 'address',
    type: 'text',
    defaultChecked: false,
    applicationType: 'profile',
    isRequired: true,
    pattern: '^[^\\s].*',
  },
  {
    id: 6,
    label: 'LinkedIn Profile',
    name: 'linkedInProfile',
    type: 'url',
    isPrefix: false,
    prefixValue: 'url',
    defaultChecked: false,
    applicationType: 'profile',
    isRequired: false,
  },
  {
    id: 7,
    label: 'Highest Education Attained',
    name: 'highestEducationAttained',
    type: 'text',
    applicationType: 'profile',
    defaultChecked: false,
    isRequired: false,
    pattern: '^[^\\s].*',
  },
  {
    id: 8,
    label: 'College/University',
    name: 'collegeUniversity',
    type: 'text',
    applicationType: 'profile',
    defaultChecked: false,
    isRequired: false,
    pattern: '^[^\\s].*',
  },
  {
    id: 9,
    label: 'GPA',
    name: 'gpa',
    type: 'text',
    defaultChecked: false,
    applicationType: 'profile',
    isRequired: false,
    pattern: '^[^\\s].*',
  },
  {
    id: 10,
    label: 'Employment Status',
    name: 'employmentStatus',
    type: 'text',
    applicationType: 'profile',
    defaultChecked: false,
    isRequired: false,
    pattern: '^[^\\s].*',
  },
  {
    id: 11,
    label: 'Desired Salary',
    name: 'desiredSalary',
    type: 'text',
    applicationType: 'profile',
    defaultChecked: false,
    isRequired: false,
    pattern: '^[^\\s].*',
  },
  {
    id: 12,
    label: 'Earliest Start Date',
    name: 'earliestStartDate',
    applicationType: 'profile',
    type: 'text',
    defaultChecked: false,
    isRequired: false,
    pattern: '^[^\\s].*',
  },
  {
    id: 13,
    label: 'Willing To Relocate',
    name: 'willingToRelocate',
    type: 'text',
    defaultChecked: false,
    applicationType: 'profile',
    isRequired: false,
    pattern: '^[^\\s].*',
  },
  {
    id: 14,
    label: 'Felony Conviction (Y/N) + Explanation',
    name: 'felonyConviction',
    type: 'radio',
    applicationType: 'profile',
    options: [
      { label: 'Yes', value: 'Yes' },
      { label: 'No', value: 'No' },
    ],
    defaultChecked: false,
    isRequired: false,
  },
  {
    id: 15,
    label: 'Languages Spoken',
    name: 'languagesSpoken',
    type: 'text',
    isRequired: false,
    applicationType: 'profile',
    pattern: '^[^\\s].*',
  },
  {
    id: 16,
    label: 'How many years of experience do you have?',
    name: 'experience',
    type: 'checkbox',
    applicationType: 'profile',
    options: [
      { label: '1 year', value: '1year' },
      { label: '2 year', value: '2year' },
      { label: '5 year', value: '5year' },
      { label: 'Other', value: 'Other' },
    ],
    defaultChecked: false,
    isRequired: false,
  },
  {
    id: 17,
    label: 'Do You have a driving license?',
    name: 'drivingLicense',
    type: 'radio',
    applicationType: 'profile',
    isRequired: false,
    options: [
      { label: 'Yes', value: 'Yes' },
      { label: 'No', value: 'No' },
    ],
    defaultChecked: false,
  },
]
