export const PlaceHolder = {
  searchPlaceholder: 'Search',
  inputPlaceholder: 'Enter subject',
  editorPlaceholder: 'Enter Messages',
  formHeadingPlaceholder: 'Enter Field Name',
  formDescriptionPlaceholder: 'Describe how people should use this field',
  formDefaultPlaceholder: 'Enter a Default Value',
  formOptionPlaceholder: 'Option 1',
  formTitle: 'Enter Form Title *',
  departmentPlaceholder: 'Enter Department Name',
  profileQuestionPlaceholder: 'Enter Question',
  experiencePlaceholder: 'Enter Experience',
  employmentPlaceholder: 'Enter email',
  employmentFullNamePlaceholder: 'Enter Full Name',
  employmentLocation: 'Enter Your Location',
  employmentDescriptionPlaceholder: 'Enter description',
  employeePhonePlaceholder: 'Enter phone',
  defaultOption: 'Please select one',
  defaultUserOption: 'Please select user',
  defaultHiringOption: 'Please select Hiring Lead',
  locationPlaceholder: 'Please Select location',
  jobDescription: 'Write Job Description',
  NoOfPosition: 'Number Of Positions',
  startSalary: 'Enter Start Salary',
  endSalary: 'Enter End Salary',
}
