export const data = [
  {
    fromfields: [
      {
        id: 0.45132781699047864,
        icon: {
          key: null,
          ref: null,
          props: {},
          _owner: null,
          _store: {},
        },
        label: 'Text Area',
        type: 'text',
        isRequired: false,
        seqNumber: 0,
        pattern: '^[^\\s].*',
        default: '',
        name: 'Description',
        description: 'enter description',
      },
      {
        id: 0.9716873482100699,
        icon: {
          key: null,
          ref: null,
          props: {},
          _owner: null,
          _store: {},
        },
        label: 'Radio Button',
        type: 'radio',
        isRequired: true,
        seqNumber: 0,
        pattern: '',
        default: '',
        name: 'Gender',
        description: 'select gender',
        option: [
          {
            id: 1,
            label: 'Male',
            value: 'Male',
            defaultChecked: true,
          },
          {
            id: 2,
            label: 'Female',
            value: 'Female',
            defaultChecked: false,
          },
        ],
      },
      {
        id: 0.5703654406998269,
        icon: {
          key: null,
          ref: null,
          props: {},
          _owner: null,
          _store: {},
        },
        label: 'Checkbox',
        type: 'checkbox',
        isRequired: true,
        seqNumber: 0,
        pattern: '',
        default: '',
        name: 'Education',
        options: [
          {
            label: 'B.tech',
            value: 'B.tech',
          },
          {
            label: 'M.tech',
            value: 'M.tech',
          },
        ],
        description: 'dasdasd',
      },
      {
        id: 0.7112921312599403,
        icon: {
          key: null,
          ref: null,
          props: {},
          _owner: null,
          _store: {},
        },
        label: 'Upload',
        type: 'file',
        isRequired: true,
        seqNumber: 0,
        pattern: '',
        default: '',
        name: 'Upload resume',
        description: 'please upload resume',
      },
      {
        id: 0.5981592323344638,
        icon: {
          key: null,
          ref: null,
          props: {},
          _owner: null,
          _store: {},
        },
        label: 'Text Field',
        type: 'text',
        isRequired: true,
        seqNumber: 0,
        pattern: '^[^\\s].*',
        default: '',
        name: 'Name',
        description: 'enter name',
      },
      {
        id: 0.16512573432187372,
        icon: {
          key: null,
          ref: null,
          props: {},
          _owner: null,
          _store: {},
        },
        label: 'Phone',
        type: 'number',
        isRequired: true,
        seqNumber: 0,
        pattern: '^[0-9]{0,}$',
        default: '',
        name: 'Phone no',
        description: 'enter mobile no',
      },
      {
        id: 0.6108283996829691,
        icon: {
          key: null,
          ref: null,
          props: {},
          _owner: null,
          _store: {},
        },
        label: 'Select',
        type: 'select',
        isRequired: false,
        seqNumber: 0,
        pattern: '',
        default: '',
        name: 'Select city',
        description: 'dasdadad',
        options: [
          {
            label: 'Bettiah',
            value: 'Bettiah',
          },
          {
            label: 'Dehradun',
            value: 'Dehradun',
          },
        ],
      },
      {
        id: 0.9091408693489138,
        icon: {
          key: null,
          ref: null,
          props: {},
          _owner: null,
          _store: {},
        },
        label: 'Date Picker',
        type: 'date',
        isRequired: true,
        seqNumber: 0,
        pattern: '',
        default: '',
        name: 'DOB',
        description: 'DOB',
      },
      {
        id: 0.5515290469976364,
        icon: {
          key: null,
          ref: null,
          props: {},
          _owner: null,
          _store: {},
        },
        label: 'Time Picker',
        type: 'time',
        isRequired: false,
        seqNumber: 0,
        pattern: '',
        default: '',
        name: 'Time',
        description: 'interview time',
      },
    ],
    seqNumber: 0,
    name: 'Form',
    requireApproval: false,
    jobPostId: '50a91c04-3124-11ee-be56-0242ac120002',
  },
  {
    fromfields: [
      {
        id: 0.5981592323344638,
        icon: {
          key: null,
          ref: null,
          props: {},
          _owner: null,
          _store: {},
        },
        label: 'Text Field',
        type: 'text',
        isRequired: true,
        seqNumber: 0,
        pattern: '^[^\\s].*',
        default: '',
        name: 'Name',
        description: 'enter name',
      },
      {
        id: 0.45132781699047864,
        icon: {
          key: null,
          ref: null,
          props: {},
          _owner: null,
          _store: {},
        },
        label: 'Text Area',
        type: 'text',
        isRequired: false,
        seqNumber: 0,
        pattern: '^[^\\s].*',
        default: '',
        name: 'Description',
        description: 'enter description',
      },
      {
        id: 0.9716873482100699,
        icon: {
          key: null,
          ref: null,
          props: {},
          _owner: null,
          _store: {},
        },
        label: 'Radio Button',
        type: 'radio',
        isRequired: true,
        seqNumber: 0,
        pattern: '',
        default: '',
        name: 'Gender',
        description: 'select gender',
        option: [
          {
            id: 1,
            label: 'Male',
            value: 'Male',
            defaultChecked: true,
          },
          {
            id: 2,
            label: 'Female',
            value: 'Female',
            defaultChecked: false,
          },
        ],
      },
      {
        id: 0.5703654406998269,
        icon: {
          key: null,
          ref: null,
          props: {},
          _owner: null,
          _store: {},
        },
        label: 'Checkbox',
        type: 'checkbox',
        isRequired: true,
        seqNumber: 0,
        pattern: '',
        default: '',
        name: 'Education',
        options: [
          {
            label: 'B.tech',
            value: 'B.tech',
          },
          {
            label: 'M.tech',
            value: 'M.tech',
          },
        ],
        description: 'dasdasd',
      },
      {
        id: 0.7112921312599403,
        icon: {
          key: null,
          ref: null,
          props: {},
          _owner: null,
          _store: {},
        },
        label: 'Upload',
        type: 'file',
        isRequired: true,
        seqNumber: 0,
        pattern: '',
        default: '',
        name: 'Upload resume',
        description: 'please upload resume',
      },
      {
        id: 0.16512573432187372,
        icon: {
          key: null,
          ref: null,
          props: {},
          _owner: null,
          _store: {},
        },
        label: 'Phone',
        type: 'number',
        isRequired: true,
        seqNumber: 0,
        pattern: '^[0-9]{0,}$',
        default: '',
        name: 'Phone no',
        description: 'enter mobile no',
      },
      {
        id: 0.6108283996829691,
        icon: {
          key: null,
          ref: null,
          props: {},
          _owner: null,
          _store: {},
        },
        label: 'Select',
        type: 'select',
        isRequired: false,
        seqNumber: 0,
        pattern: '',
        default: '',
        name: 'Select city',
        description: 'dasdadad',
        options: [
          {
            label: 'Bettiah',
            value: 'Bettiah',
          },
          {
            label: 'Dehradun',
            value: 'Dehradun',
          },
        ],
      },
      {
        id: 0.9091408693489138,
        icon: {
          key: null,
          ref: null,
          props: {},
          _owner: null,
          _store: {},
        },
        label: 'Date Picker',
        type: 'date',
        isRequired: true,
        seqNumber: 0,
        pattern: '',
        default: '',
        name: 'DOB',
        description: 'DOB',
      },
      {
        id: 0.5515290469976364,
        icon: {
          key: null,
          ref: null,
          props: {},
          _owner: null,
          _store: {},
        },
        label: 'Time Picker',
        type: 'time',
        isRequired: false,
        seqNumber: 0,
        pattern: '',
        default: '',
        name: 'Time',
        description: 'interview time',
      },
      {
        id: 0.5957682118896934,
        icon: {
          key: null,
          ref: null,
          props: {},
          _owner: null,
          _store: {},
        },
        label: 'Drag and Upload',
        type: 'file',
        isRequired: false,
        seqNumber: 0,
        pattern: '',
        default: '',
        name: 'Upload docs',
        description: 'asdasdad',
      },
    ],
    seqNumber: 0,
    name: 'Form',
    requireApproval: false,
    jobPostId: '50a91c04-3124-11ee-be56-0242ac120002',
  },
  {
    fromfields: [
      {
        id: 0.45132781699047864,
        icon: {
          key: null,
          ref: null,
          props: {},
          _owner: null,
          _store: {},
        },
        label: 'Text Area',
        type: 'text',
        isRequired: false,
        seqNumber: 0,
        pattern: '^[^\\s].*',
        default: '',
        name: 'Description',
        description: 'enter description',
      },
      {
        id: 0.9716873482100699,
        icon: {
          key: null,
          ref: null,
          props: {},
          _owner: null,
          _store: {},
        },
        label: 'Radio Button',
        type: 'radio',
        isRequired: true,
        seqNumber: 0,
        pattern: '',
        default: '',
        name: 'Gender',
        description: 'select gender',
        option: [
          {
            id: 1,
            label: 'Male',
            value: 'Male',
            defaultChecked: true,
          },
          {
            id: 2,
            label: 'Female',
            value: 'Female',
            defaultChecked: false,
          },
        ],
      },
      {
        id: 0.5703654406998269,
        icon: {
          key: null,
          ref: null,
          props: {},
          _owner: null,
          _store: {},
        },
        label: 'Checkbox',
        type: 'checkbox',
        isRequired: true,
        seqNumber: 0,
        pattern: '',
        default: '',
        name: 'Education',
        options: [
          {
            label: 'B.tech',
            value: 'B.tech',
          },
          {
            label: 'M.tech',
            value: 'M.tech',
          },
        ],
        description: 'dasdasd',
      },
      {
        id: 0.7112921312599403,
        icon: {
          key: null,
          ref: null,
          props: {},
          _owner: null,
          _store: {},
        },
        label: 'Upload',
        type: 'file',
        isRequired: true,
        seqNumber: 0,
        pattern: '',
        default: '',
        name: 'Upload resume',
        description: 'please upload resume',
      },
      {
        id: 0.5981592323344638,
        icon: {
          key: null,
          ref: null,
          props: {},
          _owner: null,
          _store: {},
        },
        label: 'Text Field',
        type: 'text',
        isRequired: true,
        seqNumber: 0,
        pattern: '^[^\\s].*',
        default: '',
        name: 'Name',
        description: 'enter name',
      },
      {
        id: 0.16512573432187372,
        icon: {
          key: null,
          ref: null,
          props: {},
          _owner: null,
          _store: {},
        },
        label: 'Phone',
        type: 'number',
        isRequired: true,
        seqNumber: 0,
        pattern: '^[0-9]{0,}$',
        default: '',
        name: 'Phone no',
        description: 'enter mobile no',
      },
      {
        id: 0.6108283996829691,
        icon: {
          key: null,
          ref: null,
          props: {},
          _owner: null,
          _store: {},
        },
        label: 'Select',
        type: 'select',
        isRequired: false,
        seqNumber: 0,
        pattern: '',
        default: '',
        name: 'Select city',
        description: 'dasdadad',
        options: [
          {
            label: 'Bettiah',
            value: 'Bettiah',
          },
          {
            label: 'Dehradun',
            value: 'Dehradun',
          },
        ],
      },
      {
        id: 0.9091408693489138,
        icon: {
          key: null,
          ref: null,
          props: {},
          _owner: null,
          _store: {},
        },
        label: 'Date Picker',
        type: 'date',
        isRequired: true,
        seqNumber: 0,
        pattern: '',
        default: '',
        name: 'DOB',
        description: 'DOB',
      },
      {
        id: 0.5515290469976364,
        icon: {
          key: null,
          ref: null,
          props: {},
          _owner: null,
          _store: {},
        },
        label: 'Time Picker',
        type: 'time',
        isRequired: false,
        seqNumber: 0,
        pattern: '',
        default: '',
        name: 'Time',
        description: 'interview time',
      },
    ],
    seqNumber: 0,
    name: 'Form',
    requireApproval: false,
    jobPostId: '50a91c04-3124-11ee-be56-0242ac120002',
  },
]
